---
    php_ppa: "php-7.0"
    doc_root: "/vagrant/web"
    sys_packages: ["git"]
    dist: precise
    php_packages: ["php7.0-cli","php7.0-curl","php7.0-common","php7.0-mysql","php7.0-gd","php7.0-intl","php7.0-opcache", "php7.0-dev"]
    pecl_packages: ["mongodb"]
